name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: gradle
    - name: Get JRE
      uses: dawidd6/action-download-artifact@v2
      with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          path: .
          workflow_conclusion: success
          repo: Google61/android-openjdk-build-multiarch
          branch: buildjre8
          name: jre8-aarch32
    - name: Move JRE
      run: mv jre8-arm-*-release.tar.xz BoardwalkJVM/src/main/assets/jre.tar.xz
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew :BoardwalkJVM:assembleDebug
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: BoardwalkJVM-debug
        path: BoardwalkJVM/build/outputs/apk/debug/BoardwalkJVM-debug.apk
