name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew :BoardwalkJVM:assembleDebug
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: BoardwalkJVM-debug
        path: BoardwalkJVM/build/outputs/apk/debug/BoardwalkJVM-debug.apk
